Repository riesentoaster/geiman01, pull requests merged in 2022-01, with the labels that each got.

#16 Nothing/squaring the circle
  README.md
  SquareTheCircle.md
  assets/Squaringthecircle.svg.png
Labels: nothing

#20 Wort zum Sonntag
  README.md
Labels: thing

#21 Add skribblio-prompt
  README.md
Labels: maybething
